### ISSUE TITLE
My weapons dont render if i inject the hack.

### ISSUE THREAD

**Issue by oofnames** [ZaresPlusX/Krunker_ZER0X#15]
IF i inject the hack my weapons dont render at alll
![Annotation 2020-03-25 134908](https://user-images.githubusercontent.com/60379676/77533395-75986b00-6e9f-11ea-8157-ab25fa5e5ce2.png)

**Comment by ZaresPlusX** [comment]
That happens some times. Try to reload the page

**Comment by oofnames** [comment]
Thanks but it has happened every single time i have injected

**Comment by oofnames** [comment]
and if i dont use the hack weapons load so its the cheat

**Comment by ZaresPlusX** [comment]
use the new version now
